package com.smallchill.api.function.modal;

import org.beetl.sql.core.annotatoin.Table;
import com.smallchill.core.annotation.BindID;
import com.smallchill.core.base.model.BaseModel;

/**
 * Generated by Blade.
 * 2016-11-26 19:17:36
 */
@Table(name = "tb_user_local")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Scan extends BaseModel {

    private Integer userId;
    private Double lat;
    private Double lon;

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLon() {
        return lon;
    }

    public void setLon(Double lon) {
        this.lon = lon;
    }
}
