package com.smallchill.api.function.modal;

import org.beetl.sql.core.annotatoin.Table;
import com.smallchill.core.annotation.BindID;
import com.smallchill.core.base.model.BaseModel;

import javax.persistence.Column;

/**
 * 好友分组成员
 * Generated by yesong.
 * 2016-11-22 18:01:39
 */
@Table(name = "tb_user_friend_grouping_member")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Ufgm extends BaseModel {

    @Column(name = "id")
    private Integer id;
    @Column(name = "ufg_id")
    private Integer ufgId;
    @Column(name = "friend_id")
    private Integer friendId;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUfgId() {
        return ufgId;
    }

    public void setUfgId(Integer ufgId) {
        this.ufgId = ufgId;
    }

    public Integer getFriendId() {
        return friendId;
    }

    public void setFriendId(Integer friendId) {
        this.friendId = friendId;
    }
}
