package com.smallchill.api.function.modal;

import org.beetl.sql.core.annotatoin.Table;
import com.smallchill.core.annotation.BindID;
import com.smallchill.core.base.model.BaseModel;

import javax.persistence.Column;

/**
 *
 * 用户-感兴趣
 * Generated by yesong.
 * 2016-11-11 11:56:50
 */
@Table(name = "tb_interest_user")
@BindID(name = "id")
@SuppressWarnings("serial")
public class UserInterest extends BaseModel {

    @Column(name = "id")
    private Integer id;
    @Column(name= "user_id")
    private Integer userId;
    @Column(name = "to_user_id")
    private Integer toUserId;
    @Column(name = "status")
    private Integer status;
    @Column(name = "create_time")
    private Long createTime;

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getToUserId() {
        return toUserId;
    }

    public void setToUserId(Integer toUserId) {
        this.toUserId = toUserId;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}
