package com.smallchill.api.function.modal;

import org.beetl.sql.core.annotatoin.Table;
import com.smallchill.core.annotation.BindID;
import com.smallchill.core.base.model.BaseModel;
import org.springframework.beans.factory.annotation.Autowired;

import javax.persistence.Column;

/**
 * 用户好友分组
 * Generated by yesong.
 * 2016-11-22 17:59:15
 */
@Table(name = "tb_user_friend_grouping")
@BindID(name = "id")
@SuppressWarnings("serial")
public class UserFriendGrouping extends BaseModel {

    @Column(name = "id")
    private Integer id;
    @Column(name = "user_id")
    private Integer userId;
    @Column(name = "name")
    private String name;
    @Column(name = "is_default")
    private Integer isDefault;

    public Integer getIsDefault() {
        return isDefault;
    }

    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
