package com.smallchill.api.function.modal;

import org.beetl.sql.core.annotatoin.Table;
import com.smallchill.core.annotation.BindID;
import com.smallchill.core.base.model.BaseModel;

/**
 * Generated by Blade.
 * 2016-10-24 18:05:06
 */
@Table(name = "tb_userinfo_professional")
@BindID(name = "ID")
@SuppressWarnings("serial")
public class UserProfessional extends BaseModel {

}
