package com.smallchill.platform.model;

import com.smallchill.core.toolbox.kit.DateKit;
import com.smallchill.core.toolbox.kit.DateTimeKit;
import com.smallchill.core.toolbox.support.DateTime;
import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.SeqID;
import org.beetl.sql.core.annotatoin.Table;
import com.smallchill.core.annotation.BindID;
import com.smallchill.core.base.model.BaseModel;

import javax.persistence.Column;

/**
 * Generated by Blade.
 * 2016-10-18 09:41:36
 */
@Table(name = "tb_user_login")
@BindID(name = "id")
@SuppressWarnings("serial")
public class UserLogin extends BaseModel {

    @Column(name = "id")
    private Integer id;
    @Column(name = "login_username")
    private String username = "";
    @Column(name = "password")
    private String password = "";
    @Column(name = "status")
    private Integer status = 0;
    @Column(name = "unlock_time")
    private Long unlockTime = -1L;
    @Column(name = "last_login_ip")
    private String lastLoginIp = "";
    @Column(name = "last_login_time")
    private Long lastLoginTime = DateTimeKit.nowLong();
    @Column(name = "create_time")
    private Long createTime;

    @AutoID
    @SeqID(name = "SEQ_NOTICE")
    public Integer getId() {
        return id;
    }

    public Long getLastLoginTime() {
        return lastLoginTime;
    }

    public void setLastLoginTime(Long lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Long getUnlockTime() {
        return unlockTime;
    }

    public void setUnlockTime(Long unlockTime) {
        this.unlockTime = unlockTime;
    }

    public String getLastLoginIp() {
        return lastLoginIp;
    }

    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public boolean isLock(){
        return this.status == 1;
    }

    public boolean isFreeze() {
        return this.status == 2;
    }
}
