package com.smallchill.platform.model;

import org.beetl.sql.core.annotatoin.Table;
import com.smallchill.core.annotation.BindID;
import com.smallchill.core.base.model.BaseModel;

/**
 * Generated by Blade.
 * 2016-10-18 09:41:36
 */
@Table(name = "tb_user_login")
@BindID(name = "id")
@SuppressWarnings("serial")
public class UserLogin extends BaseModel {

}
