package com.smallchill.platform.service;

import com.smallchill.core.base.service.IService;
import com.smallchill.platform.model.UserLogin;

/**
 * Generated by Blade.
 * 2016-10-18 09:41:36
 */
public interface UserLoginService extends IService<UserLogin> {

}
