package com.smallchill.web.controller;

import com.smallchill.web.meta.intercept.DailyAndMagazineMgrIntercept;
import com.smallchill.web.model.Daily;
import com.smallchill.web.service.DailyService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.smallchill.common.base.BaseController;
import com.smallchill.core.toolbox.ajax.AjaxResult;
import com.smallchill.core.toolbox.kit.JsonKit;

/**
 * Generated by Blade.
 * 2017-01-13 13:52:05
 */
@Controller
@RequestMapping("/daily")
public class DailyController extends BaseController {
	private static String CODE = "daily";
	private static String PERFIX = "tb_daily";
	private static String LIST_SOURCE = "DailyMgr.list";
	private static String BASE_PATH = "/web/daily/";
	private static String ARTICLE_PATH = "/web/article/";
	
	@Autowired
	DailyService service;

	@RequestMapping("/article_index")
	public String articleIndex(ModelMap mm) {
		mm.put("code", CODE);
		return ARTICLE_PATH + "article_index.html";
	}

	@RequestMapping(KEY_MAIN)
	public String index(ModelMap mm, Integer status) {
		mm.put("code", CODE);
		mm.put("status", status);
		return ARTICLE_PATH + "article.html";
	}

	@RequestMapping(KEY_ADD)
	public String add(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "daily_view.html";
	}

	@RequestMapping(KEY_EDIT + "/{id}")
	public String edit(@PathVariable String id, ModelMap mm) {
		Daily daily = service.findById(id);
		mm.put("model", JsonKit.toJson(daily));
		mm.put("id", id);
		mm.put("code", CODE);
		return BASE_PATH + "daily_view.html";
	}

	@RequestMapping(KEY_VIEW + "/{id}")
	public String view(@PathVariable String id, ModelMap mm) {
		Daily daily = service.findById(id);
		mm.put("model", JsonKit.toJson(daily));
		mm.put("id", id);
		mm.put("code", CODE);
		return BASE_PATH + "daily_view.html";
	}

	@ResponseBody
	@RequestMapping(KEY_LIST)
	public Object list(Integer status) {
		DailyAndMagazineMgrIntercept dailyAndMagazineMgrIntercept = new DailyAndMagazineMgrIntercept();
		dailyAndMagazineMgrIntercept.setStatus(status);
		Object grid = paginate(LIST_SOURCE, dailyAndMagazineMgrIntercept);
		return grid;
	}

	@ResponseBody
	@RequestMapping(KEY_SAVE)
	public AjaxResult save() {
		Daily daily = mapping(PERFIX, Daily.class);
		boolean temp = service.save(daily);
		if (temp) {
			return success(SAVE_SUCCESS_MSG);
		} else {
			return error(SAVE_FAIL_MSG);
		}
	}

	@ResponseBody
	@RequestMapping(KEY_UPDATE)
	public AjaxResult update() {
		Daily daily = mapping(PERFIX, Daily.class);
		boolean temp = service.update(daily);
		if (temp) {
			return success(UPDATE_SUCCESS_MSG);
		} else {
			return error(UPDATE_FAIL_MSG);
		}
	}

	@ResponseBody
	@RequestMapping(KEY_REMOVE)
	public AjaxResult remove(@RequestParam String ids) {
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			return success(DEL_SUCCESS_MSG);
		} else {
			return error(DEL_FAIL_MSG);
		}
	}
}
