package com.smallchill.web.controller;

import com.smallchill.api.function.modal.vo.SendVo;
import com.smallchill.common.task.TimeWorkManager;
import com.smallchill.core.constant.Cst;
import com.smallchill.core.plugins.dao.Blade;
import com.smallchill.core.plugins.dao.Db;
import com.smallchill.core.toolbox.Record;
import com.smallchill.core.toolbox.grid.GridManager;
import com.smallchill.core.toolbox.grid.JqGrid;
import com.smallchill.core.toolbox.kit.DateTimeKit;
import com.smallchill.core.toolbox.kit.StrKit;
import com.smallchill.web.meta.task.SendTimeWork;
import com.smallchill.web.meta.task.TestTimeWork;
import com.smallchill.web.model.UserInfo;
import com.smallchill.web.service.UserInfoService;
import org.apache.commons.lang3.StringUtils;
import org.beetl.sql.core.kit.CaseInsensitiveHashMap;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.smallchill.common.base.BaseController;
import com.smallchill.core.toolbox.ajax.AjaxResult;
import com.smallchill.core.toolbox.kit.JsonKit;

import javax.servlet.http.HttpServletRequest;
import java.util.ArrayList;
import java.util.List;

/**
 * Generated by Blade.
 * 2016-10-18 09:47:31
 */
@Controller
@RequestMapping("/userInfo")
public class UserInfoController extends BaseController {
	private static String CODE = "userInfo";
	private static String PERFIX = "tb_user_info";
	private static String LIST_SOURCE = "UserInfo.list";
	private static String BASE_PATH = "/web/userInfo/";
	
	@Autowired
	UserInfoService userInfoService;
	
	@RequestMapping(KEY_MAIN)
	public String index(ModelMap mm) {
		String index = "list";
		mm.put("code", CODE);
		mm.put("list", index);
		return BASE_PATH + "userInfo.html";
	}

	@RequestMapping(KEY_ADD)
	public String add(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "userInfo_view.html";
	}

	@RequestMapping(KEY_EDIT + "/{id}")
	public String edit(@PathVariable String id, ModelMap mm) {
		UserInfo userInfo = userInfoService.findById(id);
		mm.put("model", JsonKit.toJson(userInfo));
		mm.put("id", id);
		mm.put("code", CODE);
		return BASE_PATH + "userInfo_view.html";
	}

	@RequestMapping(KEY_VIEW + "/{id}")
	public String view(@PathVariable String id, ModelMap mm) {
		UserInfo userInfo = userInfoService.findById(id);
		mm.put("model", JsonKit.toJson(userInfo));
		mm.put("id", id);
		mm.put("code", CODE);
		return BASE_PATH + "userInfo_view.html";
	}

	@ResponseBody
	@RequestMapping(KEY_LIST)
	public Object list() {
		JqGrid grid = (JqGrid)paginate(LIST_SOURCE);

		Integer page = getParameterToInt("page", 1);
		Integer rows = userInfoService.findAll().size();
		String where = getParameter("where", "");
		String sidx = getParameter("sidx", "");
		String sord = getParameter("sord", "");
		String sort = getParameter("sort", "");
		String order = getParameter("order", "");

		if (StrKit.notBlank(sidx)) {
			sort = sidx + " " + sord
					+ (StrKit.notBlank(sort) ? ("," + sort) : "");
		}

		JqGrid grid1 = (JqGrid) GridManager.paginate(null, page, rows, LIST_SOURCE, where, sort, order, Cst.me().getDefaultPageFactory(), this);
		List<Integer> ids = new ArrayList<>();
		List<CaseInsensitiveHashMap> list = grid1.getRows();
		//查询结果所有ID
		for (CaseInsensitiveHashMap map : list) {
			Integer id = (Integer) map.get("userId");
			ids.add(id);
		}

		System.out.println("===================Rows===================");
		System.out.println(list.size());
		System.out.println("===================Rows===================");
		getRequest().getSession().setAttribute("userInfoIds",ids);
		getRequest().getSession().setAttribute("userInfoNum",list.size());

		return grid;
	}

	@ResponseBody
	@RequestMapping(KEY_SAVE)
	public AjaxResult save() {
		UserInfo userInfo = mapping(PERFIX, UserInfo.class);
		boolean temp = userInfoService.save(userInfo);
		if (temp) {
			return success(SAVE_SUCCESS_MSG);
		} else {
			return error(SAVE_FAIL_MSG);
		}
	}

	@ResponseBody
	@RequestMapping(KEY_UPDATE)
	public AjaxResult update() {
		UserInfo userInfo = mapping(PERFIX, UserInfo.class);
		boolean temp = userInfoService.update(userInfo);
		if (temp) {
			return success(UPDATE_SUCCESS_MSG);
		} else {
			return error(UPDATE_FAIL_MSG);
		}
	}

	@ResponseBody
	@RequestMapping(KEY_REMOVE)
	public AjaxResult remove(@RequestParam String ids) {
		int cnt = userInfoService.deleteByIds(ids);
		if (cnt > 0) {
			return success(DEL_SUCCESS_MSG);
		} else {
			return error(DEL_FAIL_MSG);
		}
	}


	//跳转改变组织状态页面
	@RequestMapping("/banned")
	public String banned(ModelMap mm,Integer id,Integer status) {
		mm.put("id", id);
		mm.put("status", status);
		return BASE_PATH +"userInfo_banned.html";
	}


	//改变组织状态(封/解)
	@ResponseBody
	@RequestMapping(value = "/setBanned")
	public AjaxResult setBanned(Integer id, Integer bannedTime ,String content,Integer status){
		try{
			userInfoService.banned(id,bannedTime,content,status);
		}catch (RuntimeException e){
			return error(SAVE_FAIL_MSG);
		}
		return success(SAVE_SUCCESS_MSG);
	}

	//消息发送页面(单发)
	@RequestMapping("/message" + "/{id}")
	public String userMessages(ModelMap mm,@PathVariable String id) {
		UserInfo userInfo = userInfoService.findById(id);
		mm.put("userInfo", userInfo);
		mm.put("userInfoNum", 0);
		mm.put("code", CODE);
		return BASE_PATH + "userInfo_message.html";
	}

	//消息发送页面(群发)
	@RequestMapping("/message")
	public String _userMessages(ModelMap mm,HttpServletRequest request) {
		UserInfo userInfo = new UserInfo();
		mm.put("userInfoNum", request.getSession().getAttribute("userInfoNum"));
		mm.put("userInfo", userInfo);
		mm.put("code", CODE);
		return BASE_PATH + "userInfo_message.html";
	}

	//消息发送
	@ResponseBody
	@RequestMapping("/send_message")
	public AjaxResult sendMessage(Integer userInfoId,Integer send,String sendTime,String title,String content) {
		try{
			Long time ;
			if(StringUtils.isNotBlank(sendTime)){
				time = DateTimeKit.parseDateTime(sendTime).getTime();
			}else {
				time = System.currentTimeMillis() + 1000;
			}
			SendVo.setToId(userInfoId);
			SendVo.setReceiveType(1);
			SendVo.setSendType(send);
			SendVo.setSendTime(time);
			SendVo.setTitle(title);
			SendVo.setContent(content);
			TimeWorkManager.create().addTimeWork("sendTimeWork",time,SendTimeWork.class);
		}catch (RuntimeException e){
			e.printStackTrace();
			return error(SEND_FAIL_MSG);
		}
		return success(SEND_SUCCESS_MSG);

	}


	//内容发送页面
	@RequestMapping(value = "/content")
	public String _userContent(ModelMap mm,HttpServletRequest request) {
		UserInfo userInfo = new UserInfo();
		mm.put("userInfoNum", request.getSession().getAttribute("userInfoNum"));
		mm.put("userInfo", userInfo);
		mm.put("code", CODE);
		return BASE_PATH + "userInfo_content.html";
	}
}
