package com.smallchill.web.controller;

import com.smallchill.web.model.UserInfo;
import com.smallchill.web.service.UserInfoService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.smallchill.common.base.BaseController;
import com.smallchill.core.toolbox.ajax.AjaxResult;
import com.smallchill.core.toolbox.kit.JsonKit;

/**
 * Generated by Blade.
 * 2016-10-18 09:47:31
 */
@Controller
@RequestMapping("/userInfo")
public class UserInfoController extends BaseController {
	private static String CODE = "userInfo";
	private static String PERFIX = "tb_user_info";
	private static String LIST_SOURCE = "UserInfo.list";
	private static String BASE_PATH = "/web/userInfo/";
	
	@Autowired
	UserInfoService service;
	
	@RequestMapping(KEY_MAIN)
	public String index(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "userInfo.html";
	}

	@RequestMapping(KEY_ADD)
	public String add(ModelMap mm) {
		mm.put("code", CODE);
		return BASE_PATH + "userInfo_view.html";
	}

	@RequestMapping(KEY_EDIT + "/{id}")
	public String edit(@PathVariable String id, ModelMap mm) {
		UserInfo userInfo = service.findById(id);
		mm.put("model", JsonKit.toJson(userInfo));
		mm.put("id", id);
		mm.put("code", CODE);
		return BASE_PATH + "userInfo_view.html";
	}

	@RequestMapping(KEY_VIEW + "/{id}")
	public String view(@PathVariable String id, ModelMap mm) {
		UserInfo userInfo = service.findById(id);
		mm.put("model", JsonKit.toJson(userInfo));
		mm.put("id", id);
		mm.put("code", CODE);
		return BASE_PATH + "userInfo_view.html";
	}

	@ResponseBody
	@RequestMapping(KEY_LIST)
	public Object list() {
		Object grid = paginate(LIST_SOURCE);
		return grid;
	}

	@ResponseBody
	@RequestMapping(KEY_SAVE)
	public AjaxResult save() {
		UserInfo userInfo = mapping(PERFIX, UserInfo.class);
		boolean temp = service.save(userInfo);
		if (temp) {
			return success(SAVE_SUCCESS_MSG);
		} else {
			return error(SAVE_FAIL_MSG);
		}
	}

	@ResponseBody
	@RequestMapping(KEY_UPDATE)
	public AjaxResult update() {
		UserInfo userInfo = mapping(PERFIX, UserInfo.class);
		boolean temp = service.update(userInfo);
		if (temp) {
			return success(UPDATE_SUCCESS_MSG);
		} else {
			return error(UPDATE_FAIL_MSG);
		}
	}

	@ResponseBody
	@RequestMapping(KEY_REMOVE)
	public AjaxResult remove(@RequestParam String ids) {
		int cnt = service.deleteByIds(ids);
		if (cnt > 0) {
			return success(DEL_SUCCESS_MSG);
		} else {
			return error(DEL_FAIL_MSG);
		}
	}
}
