package com.smallchill.web.service.impl;

import com.smallchill.web.model.ArticleShow;
import com.smallchill.web.service.ArticleShowService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;


/**
 * Generated by Blade.
 * 2017-01-13 16:15:01
 */
@Service
public class ArticleShowServiceImpl extends BaseService<ArticleShow> implements ArticleShowService {

}
