package com.smallchill.web.service.impl;

import com.smallchill.web.model.Aug;
import com.smallchill.web.service.AugService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;

/**
 * Generated by Blade.
 * 2016-11-08 17:59:49
 */
@Service
public class AugServiceImpl extends BaseService<Aug> implements AugService {

}
