package com.smallchill.web.service.impl;

import com.smallchill.web.model.GroupExtend;
import com.smallchill.web.service.GroupExtendService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;


/**
 * Generated by Blade.
 * 2016-10-25 17:46:14
 */
@Service
public class GroupExtendServiceImpl extends BaseService<GroupExtend> implements GroupExtendService {

}
