package com.smallchill.web.service.impl;

import com.smallchill.web.model.Group;
import com.smallchill.web.service.GroupService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;


/**
 * Generated by Blade.
 * 2016-10-25 17:34:42
 */
@Service
public class GroupServiceImpl extends BaseService<Group> implements GroupService {

}
