package com.smallchill.web.service.impl;

import com.smallchill.core.toolbox.Record;
import com.smallchill.web.model.GroupExtend;
import com.smallchill.web.service.GroupExtendService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;


/**
 * 组织扩展信息
 * Generated by yesong.
 * 2016-10-25 17:46:14
 */
@Service
public class GroupExtendServiceImpl extends BaseService<GroupExtend> implements GroupExtendService {

    @Override
    public Double getCost(Integer groupId) {
        String sql = "select cost from tb_group_extend where group_id = #{groupId}";
        GroupExtend ge = this.findFirst(sql, Record.create().set("groupId", groupId));
        return ge.getCost();
    }
}
