package com.smallchill.web.service.impl;

import com.smallchill.web.model.GroupBank;
import com.smallchill.web.service.GroupBankService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;

/**
 * Generated by Blade.
 * 2016-10-25 17:37:52
 */
@Service
public class GroupBankServiceImpl extends BaseService<GroupBank> implements GroupBankService {

}
