package com.smallchill.web.service.impl;

import com.smallchill.web.model.MaganizeSubscribe;
import com.smallchill.web.service.MaganizeSubscribeService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;

/**
 * Generated by yesong.
 * 2017-02-03 17:55:49
 */
@Service
public class MaganizeSubscribeServiceImpl extends BaseService<MaganizeSubscribe> implements MaganizeSubscribeService {
}
