package com.smallchill.web.service.impl;

import com.smallchill.core.plugins.dao.Blade;
import com.smallchill.core.plugins.dao.Db;
import com.smallchill.core.toolbox.Record;
import com.smallchill.core.toolbox.kit.DateKit;
import com.smallchill.core.toolbox.support.DateTime;
import com.smallchill.web.model.Maganize;
import com.smallchill.web.service.MaganizeService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Generated by Blade.
 * 2017-01-13 17:00:33
 */
@Service
public class MaganizeServiceImpl extends BaseService<Maganize> implements MaganizeService {

    /**
     * 根据杂志ID查询文章列表 按照每一天分组
     *
     * @param maganzieId 杂志ID
     * @param pagenum    当前页数
     * @param pagesize   每页显示数
     * @return map
     */
    @Override
    public Map<String, Object> listById(int maganzieId, int pagenum, int pagesize) {

        Map<String, Object> map = new HashMap<>();
        int start = 0;
        if (pagenum != 1) {
            start = (pagenum - 1) * pagesize + 1;
        }
        for (int i = start; i < pagesize; i++) {
            String timeParam = DateKit.getAfterDayDate(i, "yyyyMMdd");
            String time = DateKit.getAfterDayDate(i, "M-dd");
            map.put(time, listById(maganzieId, timeParam));
        }
        map.put("pagenum", pagenum);
        return map;
    }

    /**
     * @param maganzieId 杂志ID
     * @param time       日期 yyyyMMdd
     * @return list
     */
    private List<Record> listById(int maganzieId, String time) {
        String sql = Blade.dao().getScript("MagazineInfo.listById").getSql();
        return Db.init().selectList(sql, Record.create().set("id", maganzieId).set("time", time));
    }
}
