package com.smallchill.web.service.impl;

import com.smallchill.core.plugins.dao.Blade;
import com.smallchill.web.model.MagazineInfo;
import com.smallchill.web.service.MagazineInfoService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;

import java.util.List;


/**
 * 杂志service
 * Generated by yesong.
 * 2017-01-12 16:37:27
 */
@Service
public class MagazineInfoServiceImpl extends BaseService<MagazineInfo> implements MagazineInfoService {

    /**
     * 查询所有杂志
     * @return list
     */
    @Override
    public List<MagazineInfo> findAll2() {
        String sql = Blade.dao().getScript("MagazineInfo.listColIdAndName").getSql();
        return Blade.create(MagazineInfo.class).find(sql, null);
    }

    /**
     * 订阅
     * @param userId 当前用户ID
     * @param magazineId 杂志ID
     */
    @Override
    public void subscribe(Integer userId, Integer magazineId) {
        // TODO 判断是否已经订阅
    }

    @Override
    public void unsubscribe(Integer userId, Integer magazineId) {
        // TODO 判断是否已经订阅
    }
}
