package com.smallchill.web.service.impl;

import com.smallchill.api.function.modal.vo.MaganizeInfoVo;
import com.smallchill.core.plugins.dao.Blade;
import com.smallchill.core.plugins.dao.Db;
import com.smallchill.core.toolbox.Record;
import com.smallchill.core.toolbox.grid.JqGrid;
import com.smallchill.core.toolbox.kit.CollectionKit;
import com.smallchill.web.model.MagazineInfo;
import com.smallchill.web.service.MagazineInfoService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;

import java.util.List;


/**
 * 杂志service
 * Generated by yesong.
 * 2017-01-12 16:37:27
 */
@Service
public class MagazineInfoServiceImpl extends BaseService<MagazineInfo> implements MagazineInfoService {

    @Override
    public List<MagazineInfo> simpleListByUserId(int userId) {
        String sql = Blade.dao().getScript("MaganizeSubscribe.SimpleListByUserId").getSql();
        return find(sql, Record.create().set("userId", userId));
    }

    /**
     * 杂志列表
     * @param userId 当前用户ID
     * @param status 订阅状态 1:已订阅 2:未订阅
     * @return page
     */
    @Override
    public JqGrid<MaganizeInfoVo> list(Integer userId,Integer pid, Integer domainId, Integer status) {
        return null;
    }
}
