package com.smallchill.web.service.impl;

import com.smallchill.web.model.Maganize;
import com.smallchill.web.service.MaganizeService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;

/**
 * Generated by Blade.
 * 2017-01-13 17:00:33
 */
@Service
public class MaganizeServiceImpl extends BaseService<Maganize> implements MaganizeService {

}
