package com.smallchill.web.service.impl;

import com.smallchill.api.common.exception.PayErrorException;
import com.smallchill.api.system.model.PayConfig;
import com.smallchill.core.toolbox.kit.CommonKit;
import com.smallchill.web.model.Refund;
import com.smallchill.web.service.RefundService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Generated by Blade.
 * 2016-12-03 11:59:41
 */
@Service
public class RefundServiceImpl extends BaseService<Refund> implements RefundService {

    @Override
    public Refund refund(HttpServletRequest request, HttpServletResponse response) throws PayErrorException {
        String orderNo = CommonKit.generateSn();
        Integer userId = 20;
        Refund refund = PayConfig.refund(request, response, orderNo, userId);
        this.save(refund);
        return refund;
    }
}
