package com.smallchill.web.service.impl;

import com.smallchill.core.toolbox.Record;
import com.smallchill.web.model.UserInfoExtend;
import com.smallchill.web.service.FriendExpandService;
import com.smallchill.web.service.UserInfoExtendService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;


/**
 * 用户拓展信息serviceimpl
 * Generated by yesong.
 * 2016-12-04 12:08:17
 */
@Service
public class UserInfoExtendServiceImpl extends BaseService<UserInfoExtend> implements UserInfoExtendService {

    @Autowired
    private FriendExpandService friendExpandService;

    /**
     * 根据用户ID查询用户拓展信息
     * @param userId 用户ID
     * @return userinfoExtend
     */
    @Override
    public UserInfoExtend findByUserId(Integer userId) {
        UserInfoExtend fe = this.findFirstBy("user_id #{userId}", Record.create().set("userId", userId));
        if (fe == null) {
            fe = new UserInfoExtend();
            fe.setUserId(userId);
            fe.setAcquaintanceCount(0);
            fe.setInterestCount(0);
        }
        return fe;
    }

    /**
     * 保存用户拓展信息
     * @param userId  用户ID
     * @param interestCount 感兴趣数量
     * @param acquaintanceCount 熟人数量
     */
    @Override
    public void saveUserInfoExtend(Integer userId, int interestCount, int acquaintanceCount) {
        // tb_user_info_extend表中对每个userid只保存一次，如果表中存在该用户ID数据则update，没有则insert
        UserInfoExtend fe = this.findFirstBy("user_id #{userId}", Record.create().set("userId", userId));
        if (fe == null) {
            fe = new UserInfoExtend();
            fe.setInterestCount(interestCount);
            fe.setAcquaintanceCount(acquaintanceCount);
        }
        else {
            fe.setInterestCount(fe.getInterestCount() + interestCount);
            fe.setAcquaintanceCount(fe.getAcquaintanceCount() + acquaintanceCount);
        }
        this.save(fe);
    }
}
