package com.smallchill.web.service.impl;

import com.smallchill.core.toolbox.Record;
import com.smallchill.web.model.UserApproval;
import com.smallchill.web.model.UserGroup;
import com.smallchill.web.service.UserGroupService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;


/**
 * 组织会员
 * Generated by yesong.
 * 2016-10-28 11:08:59
 */
@Service
public class UserGroupServiceImpl extends BaseService<UserGroup> implements UserGroupService {

    private String DELETEBYUSERIDANDGROUPID_WHERE = "group_id = #{groupId} and userId = #{userId}";

}
