package com.smallchill.web.service.impl;

import com.smallchill.core.toolbox.Record;
import com.smallchill.web.model.UserApproval;
import com.smallchill.web.model.UserFriend;
import com.smallchill.web.service.UserApprovalService;
import com.smallchill.web.service.UserFriendService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;
import org.springframework.transaction.annotation.Transactional;

/**
 * Generated by Blade.
 * 2016-10-31 13:30:46
 */
@Service
public class UserFriendServiceImpl extends BaseService<UserFriend> implements UserFriendService {

    @Autowired
    private UserApprovalService userApprovalService;

    @Override
    public void proessFriend(UserFriend uf) {
    }

    /**
     * 添加好友
     * 如果好友记录不为空，则修改状态
     * @param uf 用户好友记录
     */
    @Transactional
    @Override
    public void addFriend(UserFriend uf) {
        UserFriend dict = this.getByUserIdAndFriendId(uf);
        if (dict != null) {
            dict.setStatus(0);
            this.update(dict);
            this.updateFriend(dict, 0);
        }
        else {
            uf.setStatus(0);
            uf.setType(1);
            this.save(uf);
            this.saveFriend(uf);
        }
    }



    /**
     * 删除好友
     * 逻辑删除
     *
     * @param uf 好友信息
     */
    @Transactional
    @Override
    public void delFriend(UserFriend uf) {
        String set = "status = 1";
        String where = "user_id = #{userId} and friend_id = #{friendId}";
        Record record = Record.create();
        record.put("userId", uf.getUserId());
        record.put("friendId", uf.getFriendId());
        this.updateBy(set, where, record);

        // 修改好友的好友信息状态
        UserFriend _uf = this.getByUserIdAndFriendId(uf);
        this.updateFriend(_uf, 1);

        // 修改审核信息状态
        UserApproval ua = new UserApproval();
        ua.setFromUserId(uf.getUserId());
        ua.setToUserId(uf.getFriendId());
        userApprovalService.resetStatus(ua);
    }

    @Override
    public UserFriend getByUserIdAndFriendId(UserFriend uf) {
        String sql = "user_id = #{userId} and friend_id = #{friendId}";
        Record record = Record.create();
        record.put("userId", uf.getUserId());
        record.put("friendId", uf.getFriendId());
        return this.findFirstBy(sql, record);
    }

    @Override
    public void saveFriend(UserFriend uf) {
        UserFriend _friend = new UserFriend();
        _friend.setUserId(uf.getFriendId());
        _friend.setFriendId(uf.getUserId());
        _friend.setType(uf.getType());
        _friend.setStatus(0);
        this.save(_friend);
    }

    @Override
    public void updateFriend(UserFriend uf, int status) {
        UserFriend _friend = new UserFriend();
        _friend.setUserId(uf.getFriendId());
        _friend.setFriendId(uf.getUserId());

        _friend = this.getByUserIdAndFriendId(_friend);
        _friend.setStatus(status);
        this.update(_friend);
    }
}