package com.smallchill.web.service.impl;

import com.smallchill.core.shiro.ShiroKit;
import com.smallchill.core.toolbox.Record;
import com.smallchill.web.model.Group;
import com.smallchill.web.model.GroupApproval;
import com.smallchill.web.model.UserApproval;
import com.smallchill.web.model.UserGroup;
import com.smallchill.web.service.GroupApprovalService;
import com.smallchill.web.service.UserGroupService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;
import org.springframework.transaction.annotation.Transactional;


/**
 * 组织会员
 * Generated by yesong.
 * 2016-10-28 11:08:59
 */
@Service
public class UserGroupServiceImpl extends BaseService<UserGroup> implements UserGroupService {

    private String DELETEBYUSERIDANDGROUPID_WHERE = "group_id = #{groupId} AND user_id = #{userId}";

    @Autowired
    GroupApprovalService groupApprovalService;

    @Override
    @Transactional
    public void removeUser(Integer id) {
        Group group = (Group) ShiroKit.getSession().getAttribute("groupAdmin");
        this.deleteBy(DELETEBYUSERIDANDGROUPID_WHERE,Record.create().set("groupId",group.getId()).set("userId",id));
        GroupApproval groupApproval = groupApprovalService.findFirstBy(DELETEBYUSERIDANDGROUPID_WHERE,Record.create().set("groupId",group.getId()).set("userId",id));
        if(groupApproval!=null){
            groupApproval.setStatus(3);
            groupApprovalService.update(groupApproval);
        }
    }
}
