package com.smallchill.web.service.impl;

import com.smallchill.web.model.UserApproval;
import com.smallchill.web.service.UserApprovalService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;

/**
 * Generated by Blade.
 * 2016-10-28 14:31:09
 */
@Service
public class UserApprovalServiceImpl extends BaseService<UserApproval> implements UserApprovalService {

}
