package com.smallchill.api.function.service.impl;

import com.smallchill.api.function.modal.ActivityApply;
import com.smallchill.api.function.service.ActivityApplyService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;

/**
 * Generated by Blade.
 * 2017-02-13 14:25:58
 */
@Service
public class ActivityApplyServiceImpl extends BaseService<ActivityApply> implements ActivityApplyService {

}
