package com.smallchill.api.function.service.impl;

import com.smallchill.api.function.modal.GroupInterest;
import com.smallchill.api.function.service.GroupInterestService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;

/**
 * 组织感兴趣
 * Generated by yesong.
 * 2016-11-11 12:00:57
 */
@Service
public class GroupInterestServiceImpl extends BaseService<GroupInterest> implements GroupInterestService {

}
