package com.smallchill.api.function.service.impl;

import com.smallchill.api.function.modal.GroupUserRecord;
import com.smallchill.api.function.service.GroupUserRecordService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;


/**
 * Generated by Blade.
 * 2016-11-18 18:37:00
 */
@Service
public class GroupUserRecordServiceImpl extends BaseService<GroupUserRecord> implements GroupUserRecordService {

}
