package com.smallchill.api.function.service.impl;

import com.smallchill.api.function.modal.Message;
import com.smallchill.api.function.service.MessageService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;

import java.util.List;

/**
 * Generated by Blade.
 * 2016-10-27 17:24:13
 */
@Service
public abstract class MessageServiceImpl extends BaseService<Message> implements MessageService {


}
