package com.smallchill.api.function.service.impl;

import com.smallchill.api.function.modal.vo.Groupvo;
import com.smallchill.api.function.modal.vo.UserVo;
import com.smallchill.api.function.service.ScanService;
import com.smallchill.web.service.GroupService;
import com.smallchill.web.service.UserInfoService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;


/**
 * Generated by Blade.
 * 2016-11-26 19:17:36
 */
@Service
public class ScanServiceImpl implements ScanService {

    @Autowired
    private UserInfoService userInfoService;

    @Autowired
    private GroupService groupService;

    @Override
    public UserVo scanUser(Integer userId, Integer toUserId) {
        UserVo userVo = userInfoService.findUserInfoDetail(userId, toUserId, null);

        return userVo;
    }

    @Override
    public Groupvo scanGroup(Integer userId, Integer groupId) {
        return null;
    }
}
