package com.smallchill.api.function.service.impl;

import com.smallchill.api.function.modal.Ufgm;
import com.smallchill.api.function.service.UfgmService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;


/**
 * 好友分组成员
 * Generated by yesong.
 * 2016-11-22 18:01:39
 */
@Service
public class UfgmServiceImpl extends BaseService<Ufgm> implements UfgmService {

}
