package com.smallchill.api.function.service.impl;

import com.smallchill.api.function.modal.UserDomain;
import com.smallchill.api.function.service.UserDomainService;
import com.smallchill.core.base.service.BaseService;
import org.springframework.stereotype.Service;


/**
 * Generated by Blade.
 * 2016-10-24 17:47:08
 */
@Service
public class UserDomainServiceImpl extends BaseService<UserDomain> implements UserDomainService {


}
