package com.smallchill.api.function.service.impl;

import com.smallchill.api.function.modal.UserLastReadTime;
import com.smallchill.api.function.service.UserLastReadTimeService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;

/**
 * Generated by Blade.
 * 2016-11-04 17:35:21
 */
@Service
public class UserLastReadTimeServiceImpl extends BaseService<UserLastReadTime> implements UserLastReadTimeService {

}
