package com.smallchill.api.function.service.impl;

import com.smallchill.api.function.modal.UserFriendGrouping;
import com.smallchill.api.function.service.UserFriendGroupingService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;


/**
 * Generated by Blade.
 * 2016-11-22 17:59:15
 */
@Service
public class UserFriendGroupingServiceImpl extends BaseService<UserFriendGrouping> implements UserFriendGroupingService {

}
