package com.smallchill.api.function.service.impl;

import com.smallchill.api.function.modal.UserProfessional;
import com.smallchill.api.function.service.UserprofessionalService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;

/**
 * Generated by Blade.
 * 2016-10-24 18:05:06
 */
@Service
public class UserprofessionalServiceImpl extends BaseService<UserProfessional> implements UserprofessionalService {

}
