package com.smallchill.api.function.service.impl;

import com.smallchill.api.function.modal.UserInterest;
import com.smallchill.api.function.service.UserInterestService;
import org.springframework.stereotype.Service;
import com.smallchill.core.base.service.BaseService;


/**
 * Generated by Blade.
 * 2016-11-11 11:56:50
 */
@Service
public class UserInterestServiceImpl extends BaseService<UserInterest> implements UserInterestService {

}
