package com.smallchill.web.service;

import com.smallchill.core.base.service.IService;
import com.smallchill.web.model.Article;
import org.springframework.web.multipart.MultipartRequest;

/**
 * 文章service
 * Generated by yesong.
 * 2017-01-11 14:36:12
 */
public interface ArticleService extends IService<Article>{

    void create(Article article, MultipartRequest multipartRequest, String obj, boolean isUserId);
}
