package com.smallchill.web.service;

import com.smallchill.core.base.service.IService;
import com.smallchill.web.model.ArticleShow;

/**
 * Generated by Blade.
 * 2017-01-13 16:15:01
 */
public interface ArticleShowService extends IService<ArticleShow>{

}
