package com.smallchill.web.service;

import com.smallchill.core.base.service.IService;
import com.smallchill.core.toolbox.Record;
import com.smallchill.web.model.Daily;

import java.util.List;

/**
 * 日报service
 * Generated by yesong.
 * 2017-01-13 13:52:05
 */
public interface DailyService extends IService<Daily>{

    /**
     * 查询日报列表
     * @param userId 当前用户ID
     * @return 日报列表
     */
    List<Record> simpleListByUserId(Integer userId);

    /**
     * 查询用户日报
     * @param userId 当前用户ID
     * @return result
     */
    List<Record> listByUserId(Integer userId);
}
