package com.smallchill.web.service;

import com.smallchill.core.base.service.IService;
import com.smallchill.core.toolbox.Record;
import com.smallchill.web.model.Daily;

import java.util.List;

/**
 * 日报service
 * Generated by yesong.
 * 2017-01-13 13:52:05
 */
public interface DailyService extends IService<Daily>{

    /**
     * 查询所有日报机构
     * @return list
     */
    List<Record> findAllDailys();
}
