package com.smallchill.web.service;

import com.smallchill.core.base.service.IService;
import com.smallchill.core.toolbox.grid.JqGrid;
import com.smallchill.web.model.Group;
import com.smallchill.web.model.vo.GroupVo;

/**
 * Generated by Blade.
 * 2016-10-25 17:34:42
 */
public interface GroupService extends IService<Group> {

    /**
     * 保存组织信息
     *
     * @param groupVo 组织信息
     */
    void saveGroup(GroupVo groupVo);

    /**
     * 编辑组织信息
     *
     * @param groupVo 组织信息
     */
    void editGroup(GroupVo groupVo);

    JqGrid page(String source);

    /**
     * 申请审批-批准
     *
     * @param groupId 组织ID
     * @param userId  用户ID
     */
    void approval(Integer groupId, Integer userId);

    /**
     * 申请审批-拒绝
     *
     * @param groupId 组织Id
     * @param userId  用户ID
     */
    void refuse(Integer groupId, Integer userId);

    /**
     * 申请审批-拉黑
     * 被拉黑的用户无法再次加入组织
     *
     * @param groupId 组织ID
     * @param userId  用户ID
     */
    void blank(Integer groupId, Integer userId);

    /**
     * 申请审批-移除黑名单
     * 被移除黑名单的用户在组织里的状态改为退出
     *
     * @param groupId 组织ID
     * @param userId  用户ID
     */
    void unblank(Integer groupId, Integer userId);
}
