package com.smallchill.web.service;

import com.smallchill.core.base.service.IService;
import com.smallchill.web.model.GroupExtend;

/**
 * Generated by Blade.
 * 2016-10-25 17:46:14
 */
public interface GroupExtendService extends IService<GroupExtend>{

}
