package com.smallchill.web.service;

import com.smallchill.core.base.service.IService;
import com.smallchill.web.model.GroupBank;

/**
 * Generated by Blade.
 * 2016-10-25 17:37:52
 */
public interface GroupBankService extends IService<GroupBank> {

}
