package com.smallchill.web.service;

import com.smallchill.core.base.service.IService;
import com.smallchill.web.model.Group;

/**
 * Generated by Blade.
 * 2016-10-25 17:34:42
 */
public interface GroupService extends IService<Group>{

}
