package com.smallchill.web.service;

import com.smallchill.core.base.service.IService;
import com.smallchill.web.model.MaganizeSubscribe;

/**
 * Generated by yesong.
 * 2017-02-03 17:55:49
 */
public interface MaganizeSubscribeService extends IService<MaganizeSubscribe>{

}
