package com.smallchill.web.service;

import com.smallchill.core.base.service.IService;
import com.smallchill.core.toolbox.Record;
import com.smallchill.web.model.Maganize;

import java.util.List;
import java.util.Map;

/**
 * Generated by Blade.
 * 2017-01-13 17:00:33
 */
public interface MaganizeService extends IService<Maganize> {

    public Map<String, Object> listById(int maganzieId, int pagenum, int pagesize);
}
