package com.smallchill.web.service;

import com.smallchill.core.base.service.IService;
import com.smallchill.web.model.Maganize;

/**
 * Generated by Blade.
 * 2017-01-13 17:00:33
 */
public interface MaganizeService extends IService<Maganize>{

}
