package com.smallchill.web.service;

import com.smallchill.api.common.exception.PayErrorException;
import com.smallchill.core.base.service.IService;
import com.smallchill.web.model.Refund;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Generated by Blade.
 * 2016-12-03 11:59:41
 */
public interface RefundService extends IService<Refund>{

    Refund refund(HttpServletRequest request, HttpServletResponse response) throws PayErrorException;
}
