package com.smallchill.web.service;

import com.smallchill.core.base.service.IService;
import com.smallchill.web.model.UserGroup;

/**
 * Generated by Blade.
 * 2016-10-28 11:08:59
 */
public interface UserGroupService extends IService<UserGroup> {


}
