package com.smallchill.web.service;

import com.smallchill.core.base.service.IService;
import com.smallchill.web.model.UserInfoExtend;

/**
 * Generated by Blade.
 * 2016-12-04 12:08:17
 */
public interface UserInfoExtendService extends IService<UserInfoExtend>{

    /**
     * 根据用户ID查询用户拓展信息
     * @param userId 用户ID
     * @return userinfoExtend
     */
    UserInfoExtend findByUserId(Integer userId);

    /**
     * 保存用户拓展信息
     * @param userId  用户ID
     * @param interestCount 感兴趣数量
     * @param acquaintanceCount 熟人数量
     */
    void saveUserInfoExtend(Integer userId, int interestCount, int acquaintanceCount);
}
