package com.smallchill.web.service;

import com.smallchill.core.base.service.IService;
import com.smallchill.web.model.UserApproval;
import com.smallchill.web.model.UserGroup;

/**
 * 用户组织关系
 * Generated by yesong.
 * 2016-10-28 11:08:59
 */
public interface UserGroupService extends IService<UserGroup> {

}
