package com.smallchill.web.service;

import com.smallchill.core.base.service.IService;
import com.smallchill.web.model.UserApproval;

/**
 * Generated by Blade.
 * 2016-10-28 14:31:09
 */
public interface UserApprovalService extends IService<UserApproval>{

}
