package com.smallchill.web.service;

import com.smallchill.core.base.service.IService;
import com.smallchill.web.model.UserApproval;

/**
 * 用户审核
 * Generated by yesong.
 * 2016-10-28 14:31:09
 */
public interface UserApprovalService extends IService<UserApproval>{

    /**
     * 发送审核申请-单向；
     * 只发送给接收用户
     * 1.组织审核通过后
     * 2.通过共同熟人结识
     * 3.扫二维码结识
     * 4.附近的人结识
     * 5.熟人的熟人结识
     */
    void toUserOneWay(UserApproval ua);

    /**
     * 发送审核申请-双向；
     * 同时发送给接收用户和发送用户
     * 1.引荐
     */
    void toUserTwoWay(UserApproval ua);

    /**
     * 发送审核申请给组织
     * 1.通过组织成员结识
     * 2.通过活动临时群
     * 3.通过查看交集
     */
    void toGroup(UserApproval ua);

    /**
     * 组织审核
     * 发送审核消息给接收用户
     */
    void groupApproval(UserApproval ua);

    /**
     * 用户审核
     */
    void userApproval(UserApproval ua);
}
