package com.smallchill.web.service;

import com.smallchill.api.function.modal.vo.UserVo;
import com.smallchill.core.base.service.IService;
import com.smallchill.web.model.UserFriend;

import java.util.List;

/**
 * Generated by Blade.
 * 2016-10-31 13:30:46
 */
public interface UserFriendService extends IService<UserFriend> {

    /**
     * 处理好友
     *
     * @param uf
     */
    void proessFriend(UserFriend uf);

    /**
     * 添加好友
     *
     * @param uf
     */
    void addFriend(UserFriend uf);

    /**
     * 删除好友
     *
     * @param uf
     */
    void delFriend(UserFriend uf);

    /**
     * 删除熟人
     * @param uf
     */
    void delAcquaintances(UserFriend uf);

    /**
     * 加入黑名单
     * @param uf
     */
    void blank(UserFriend uf);

    /**
     * 根据用户ID查询好友信息
     *
     * @param uf
     * @return
     */
    UserFriend getByUserIdAndFriendId(UserFriend uf);

    /**
     * 给添加的好友也添加一条还有信息
     *
     * @param uf 好友信息
     */
    void saveFriend(UserFriend uf);

    /**
     * 修改好友的好友状态
     * @param uf 好友信息
     * @param status 状态
     */
    void updateFriend(UserFriend uf, int status);

    /**
     * 查看朋友的熟人
     * @param userId  用户ID
     * @param toUserId 目标用户ID
     * @return uservos
     */
    List<UserVo> findAcquaintancesByUserId(Integer userId, Integer toUserId);
}