package com.smallchill.web.model;

import org.beetl.sql.core.annotatoin.Table;
import com.smallchill.core.annotation.BindID;
import com.smallchill.core.base.model.BaseModel;

import javax.persistence.Column;

/**
 * 文章Show
 * Generated by yesong.
 * 2017-01-13 16:15:01
 */
@Table(name = "tb_article_show")
@BindID(name = "id")
@SuppressWarnings("serial")
public class ArticleShow extends BaseModel {

    @Column(name = "id")
    private Integer id;
    @Column(name = "article_id")
    private Integer articleId;
    @Column(name = "to_id")
    private Integer toId;
    @Column(name = "type")
    private Integer type;
    @Column(name = "create_time")
    private Long createTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getArticleId() {
        return articleId;
    }

    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    public Integer getToId() {
        return toId;
    }

    public void setToId(Integer toId) {
        this.toId = toId;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}
