package com.smallchill.web.model;

import org.beetl.sql.core.annotatoin.Table;
import com.smallchill.core.annotation.BindID;
import com.smallchill.core.base.model.BaseModel;

import javax.persistence.Column;

/**
 * 文章
 * Generated by yesong.
 * 2017-01-11 14:36:12
 */
@Table(name = "tb_article")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Article extends BaseModel {

    @Column(name = "id")
    private Integer id;
    @Column(name = "title")
    private String title;
    @Column(name = "content")
    private String content;
    @Column(name = "cover")
    private String cover;
    @Column(name = "article_type")
    private Integer articleType;
    @Column(name = "from_id")
    private Integer fromId;
    @Column(name = "from_type")
    private Integer fromType;
    @Column(name = "reading_quantity")
    private Integer readingQuantity;
    @Column(name = "interest_quantity")
    private Integer interestQuantity;
    @Column(name = "forwarding_quantity")
    private Integer forwardingQuantity;
    @Column(name = "start_time")
    private Long startTime;
    @Column(name = "end_time")
    private Long endTime;
    @Column(name = "status")
    private Integer status;
    @Column(name = "reason")
    private Integer reason;
    @Column(name = "create_time")
    private Long createTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getCover() {
        return cover;
    }

    public void setCover(String cover) {
        this.cover = cover;
    }

    public Integer getArticleType() {
        return articleType;
    }

    public void setArticleType(Integer articleType) {
        this.articleType = articleType;
    }

    public Integer getFromId() {
        return fromId;
    }

    public void setFromId(Integer fromId) {
        this.fromId = fromId;
    }

    public Integer getFromType() {
        return fromType;
    }

    public void setFromType(Integer fromType) {
        this.fromType = fromType;
    }

    public Integer getReadingQuantity() {
        return readingQuantity;
    }

    public void setReadingQuantity(Integer readingQuantity) {
        this.readingQuantity = readingQuantity;
    }

    public Integer getInterestQuantity() {
        return interestQuantity;
    }

    public void setInterestQuantity(Integer interestQuantity) {
        this.interestQuantity = interestQuantity;
    }

    public Integer getForwardingQuantity() {
        return forwardingQuantity;
    }

    public void setForwardingQuantity(Integer forwardingQuantity) {
        this.forwardingQuantity = forwardingQuantity;
    }

    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getReason() {
        return reason;
    }

    public void setReason(Integer reason) {
        this.reason = reason;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}
