package com.smallchill.web.model;

import org.beetl.sql.core.annotatoin.Table;
import com.smallchill.core.annotation.BindID;
import com.smallchill.core.base.model.BaseModel;

/**
 * Generated by Blade.
 * 2016-10-25 17:46:14
 */
@Table(name = "tb_group_extend")
@BindID(name = "id")
@SuppressWarnings("serial")
public class GroupTag extends BaseModel {

}
