package com.smallchill.web.model;

import org.beetl.sql.core.annotatoin.AutoID;
import org.beetl.sql.core.annotatoin.SeqID;
import org.beetl.sql.core.annotatoin.Table;
import com.smallchill.core.annotation.BindID;
import com.smallchill.core.base.model.BaseModel;

import javax.persistence.Column;

/**
 * 组织基本信息
 * Generated by yesong.
 * 2016-10-25 17:34:42
 */
@Table(name = "tb_group")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Group extends BaseModel {

    @Column(name = "id")
    private Integer id;
    @Column(name = "name")
    private String name;
    @Column(name = "avater")
    private String avater;


    @Column(name = "type")
    private Integer type;
    @Column(name = "province")
    private Integer province;
    @Column(name = "city")
    private Integer city;
    @Column(name = "targat")
    private String targat;
    @Column(name = "activity_count")
    private Integer activityCount = 0;
    @Column(name = "member_count")
    private Integer memberCount = 0;
    @Column(name = "admin_count")
    private Integer adminCount = 0;
    @Column(name = "status")
    private Integer status = 0;

    @Column(name = "create_time")
    private Long createTime;

    @Column(name = "title1")
    private String title1;
    @Column(name = "content1")
    private String content1;
    @Column(name = "is_open1")
    private Integer isOpen1;
    @Column(name = "title2")
    private String title2;
    @Column(name = "content2")
    private String content2;
    @Column(name = "is_open2")
    private Integer isOpen2;
    @Column(name = "title3")
    private String title3;
    @Column(name = "content3")
    private String content3;
    @Column(name = "is_open3")
    private Integer isOpen3;

    public Integer getIsOpen1() {
        return isOpen1;
    }

    public void setIsOpen1(Integer isOpen1) {
        this.isOpen1 = isOpen1;
    }

    public Integer getIsOpen2() {
        return isOpen2;
    }

    public void setIsOpen2(Integer isOpen2) {
        this.isOpen2 = isOpen2;
    }

    public Integer getIsOpen3() {
        return isOpen3;
    }

    public void setIsOpen3(Integer isOpen3) {
        this.isOpen3 = isOpen3;
    }

    public String getTitle1() {
        return title1;
    }

    public void setTitle1(String title1) {
        this.title1 = title1;
    }

    public String getContent1() {
        return content1;
    }

    public void setContent1(String content1) {
        this.content1 = content1;
    }

    public String getTitle2() {
        return title2;
    }

    public void setTitle2(String title2) {
        this.title2 = title2;
    }

    public String getContent2() {
        return content2;
    }

    public void setContent2(String content2) {
        this.content2 = content2;
    }

    public String getTitle3() {
        return title3;
    }

    public void setTitle3(String title3) {
        this.title3 = title3;
    }

    public String getContent3() {
        return content3;
    }

    public void setContent3(String content3) {
        this.content3 = content3;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    @AutoID
    @SeqID(name = "SEQ_DEMO")
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAvater() {
        return avater;
    }

    public void setAvater(String avater) {
        this.avater = avater;
    }


    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getProvince() {
        return province;
    }

    public void setProvince(Integer province) {
        this.province = province;
    }

    public Integer getCity() {
        return city;
    }

    public void setCity(Integer city) {
        this.city = city;
    }

    public String getTargat() {
        return targat;
    }

    public void setTargat(String targat) {
        this.targat = targat;
    }

    public Integer getActivityCount() {
        return activityCount;
    }

    public void setActivityCount(Integer activityCount) {
        this.activityCount = activityCount;
    }

    public Integer getMemberCount() {
        return memberCount;
    }

    public void setMemberCount(Integer memberCount) {
        this.memberCount = memberCount;
    }

    public Integer getAdminCount() {
        return adminCount;
    }

    public void setAdminCount(Integer adminCount) {
        this.adminCount = adminCount;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }


}
