package com.smallchill.web.model;

import org.beetl.sql.core.annotatoin.Table;
import com.smallchill.core.annotation.BindID;
import com.smallchill.core.base.model.BaseModel;

import javax.persistence.Column;

/**
 * Generated by Blade.
 * 2017-01-12 16:37:27
 */
@Table(name = "tb_magazine_info")
@BindID(name = "id")
@SuppressWarnings("serial")
public class MagazineInfo extends BaseModel {
    @Column(name = "id")
    private Integer id;
    @Column(name = "cover")
    private String cover;
    @Column(name = "name")
    private String name;
    @Column(name = "domain_pid")
    private Integer domainPid;
    @Column(name = "domain_id")
    private Integer domainId;
    @Column(name = "group_id")
    private Integer groupId;
    @Column(name = "status")
    private Integer status;
    @Column(name = "create_admin_id")
    private Integer createAdminId;
    @Column(name = "audit_admin_id")
    private Integer auditAdminId;
    @Column(name = "audit_time")
    private Long auditTime;
    @Column(name = "create_time")
    private Long createTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCover() {
        return cover;
    }

    public void setCover(String cover) {
        this.cover = cover;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getDomainPid() {
        return domainPid;
    }

    public void setDomainPid(Integer domainPid) {
        this.domainPid = domainPid;
    }

    public Integer getDomainId() {
        return domainId;
    }

    public void setDomainId(Integer domainId) {
        this.domainId = domainId;
    }

    public Integer getGroupId() {
        return groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Integer getCreateAdminId() {
        return createAdminId;
    }

    public void setCreateAdminId(Integer createAdminId) {
        this.createAdminId = createAdminId;
    }

    public Integer getAuditAdminId() {
        return auditAdminId;
    }

    public void setAuditAdminId(Integer auditAdminId) {
        this.auditAdminId = auditAdminId;
    }

    public Long getAuditTime() {
        return auditTime;
    }

    public void setAuditTime(Long auditTime) {
        this.auditTime = auditTime;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}
