package com.smallchill.web.model;

import org.beetl.sql.core.annotatoin.Table;
import com.smallchill.core.annotation.BindID;
import com.smallchill.core.base.model.BaseModel;

import javax.persistence.Column;

/**
 * Generated by Blade.
 * 2017-02-03 17:55:49
 */
@Table(name = "tb_magazine_subscribe")
@BindID(name = "id")
@SuppressWarnings("serial")
public class MaganizeSubscribe extends BaseModel {

    @Column(name = "id")
    private Integer id;
    @Column(name = "maganize_id")
    private Integer maganizeId;
    @Column(name = "user_id")
    private Integer userId;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getMaganizeId() {
        return maganizeId;
    }

    public void setMaganizeId(Integer maganizeId) {
        this.maganizeId = maganizeId;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}
