package com.smallchill.web.model;

import com.smallchill.core.annotation.BindID;
import com.smallchill.core.base.model.BaseModel;
import org.beetl.sql.core.annotatoin.Table;

import javax.persistence.Column;

/**
 * 提现设置
 * Generated by shilong.
 * 2016-12-01 13:21:42
 */
@Table(name = "tb_poundage")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Poundage extends BaseModel{

    @Column(name = "id")
    private Integer id;

    @Column(name = "rate")
    private Double rate;

    @Column(name = "num")
    private Integer num;

    @Column(name = "amount")
    private Double amount;

    @Column(name = "update_time")
    private Long updateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Double getRate() {
        return rate;
    }

    public void setRate(Double rate) {
        this.rate = rate;
    }

    public Integer getNum() {
        return num;
    }

    public void setNum(Integer num) {
        this.num = num;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public Long getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}
