package com.smallchill.web.model;

import org.beetl.sql.core.annotatoin.Table;
import com.smallchill.core.annotation.BindID;
import com.smallchill.core.base.model.BaseModel;

import javax.persistence.Column;

/**
 * 退款记录表
 * Generated by yesong.
 * 2016-12-03 11:59:41
 */
@Table(name = "tb_refund")
@BindID(name = "id")
@SuppressWarnings("serial")
public class Refund extends BaseModel {
    @Column(name = "id")
    private Integer id;
    @Column(name = "user_id")
    private Integer userId;
    @Column(name = "order_no")
    private String orderNo;
    @Column(name = "refund_type")
    private Integer refundType; // 退款原因 1:会费
    @Column(name = "result_code")
    private String resultCode;// 返回码SUCCESS/FAIL SUCCESS退款申请接收成功，结果通过退款查询接口查询 FAIL 提交业务失败
    @Column(name = "err_code")
    private String errCode;// 错误码
    @Column(name = "err_code_des")
    private String errCodeDes; // 结果信息描述
    @Column(name = "out_trade_no")
    private String outTradeNo; // 商户系统内部的订单号
    @Column(name = "transaction_id")
    private String transactionId; // 微信订单号
    @Column(name = "outRefundNo")
    private String out_refund_no;
    @Column(name = "refund_id")
    private String refundId;
    @Column(name = "refund_channel")
    private String refundChannel;
    @Column(name = "refund_fee")
    private Integer refundFee;
    @Column(name = "settlement_refund_fee")
    private Integer settlementRefundFee;
    @Column(name = "total_fee")
    private Integer totalFee;
    @Column(name = "settlement_total_fee")
    private Integer settlementTotalFee;
    @Column(name = "cash_fee")
    private Integer cashFee;
    @Column(name = "cash_refund_fee")
    private Integer cashRefundFee;
    @Column(name = "coupon_type_$n")
    private String couponType$n;
    @Column(name = "coupon_refund_fee_$n")
    private Integer couponRefundFee$n;
    @Column(name = "coupon_refund_count_$n")
    private Integer couponRefundCount$n;
    @Column(name = "coupon_refund_batch_id_$n_$m")
    private String couponRefundBatchId$n$m;
    @Column(name = "coupon_refund_id_$n_$m")
    private String couponRefundId$n$m;
    @Column(name = "coupon_refund_fee_$n_$m")
    private Integer couponRefundFee$n$m;
    @Column(name = "create_time")
    private Long createTime;

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getRefundType() {
        return refundType;
    }

    public void setRefundType(Integer refundType) {
        this.refundType = refundType;
    }

    public String getResultCode() {
        return resultCode;
    }

    public void setResultCode(String resultCode) {
        this.resultCode = resultCode;
    }

    public String getErrCode() {
        return errCode;
    }

    public void setErrCode(String errCode) {
        this.errCode = errCode;
    }

    public String getErrCodeDes() {
        return errCodeDes;
    }

    public void setErrCodeDes(String errCodeDes) {
        this.errCodeDes = errCodeDes;
    }

    public String getOutTradeNo() {
        return outTradeNo;
    }

    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo;
    }

    public String getTransactionId() {
        return transactionId;
    }

    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    public String getOut_refund_no() {
        return out_refund_no;
    }

    public void setOut_refund_no(String out_refund_no) {
        this.out_refund_no = out_refund_no;
    }

    public String getRefundId() {
        return refundId;
    }

    public void setRefundId(String refundId) {
        this.refundId = refundId;
    }

    public String getRefundChannel() {
        return refundChannel;
    }

    public void setRefundChannel(String refundChannel) {
        this.refundChannel = refundChannel;
    }

    public Integer getRefundFee() {
        return refundFee;
    }

    public void setRefundFee(Integer refundFee) {
        this.refundFee = refundFee;
    }

    public Integer getSettlementRefundFee() {
        return settlementRefundFee;
    }

    public void setSettlementRefundFee(Integer settlementRefundFee) {
        this.settlementRefundFee = settlementRefundFee;
    }

    public Integer getTotalFee() {
        return totalFee;
    }

    public void setTotalFee(Integer totalFee) {
        this.totalFee = totalFee;
    }

    public Integer getSettlementTotalFee() {
        return settlementTotalFee;
    }

    public void setSettlementTotalFee(Integer settlementTotalFee) {
        this.settlementTotalFee = settlementTotalFee;
    }

    public Integer getCashFee() {
        return cashFee;
    }

    public void setCashFee(Integer cashFee) {
        this.cashFee = cashFee;
    }

    public Integer getCashRefundFee() {
        return cashRefundFee;
    }

    public void setCashRefundFee(Integer cashRefundFee) {
        this.cashRefundFee = cashRefundFee;
    }

    public String getCouponType$n() {
        return couponType$n;
    }

    public void setCouponType$n(String couponType$n) {
        this.couponType$n = couponType$n;
    }

    public Integer getCouponRefundFee$n() {
        return couponRefundFee$n;
    }

    public void setCouponRefundFee$n(Integer couponRefundFee$n) {
        this.couponRefundFee$n = couponRefundFee$n;
    }

    public Integer getCouponRefundCount$n() {
        return couponRefundCount$n;
    }

    public void setCouponRefundCount$n(Integer couponRefundCount$n) {
        this.couponRefundCount$n = couponRefundCount$n;
    }

    public String getCouponRefundBatchId$n$m() {
        return couponRefundBatchId$n$m;
    }

    public void setCouponRefundBatchId$n$m(String couponRefundBatchId$n$m) {
        this.couponRefundBatchId$n$m = couponRefundBatchId$n$m;
    }

    public String getCouponRefundId$n$m() {
        return couponRefundId$n$m;
    }

    public void setCouponRefundId$n$m(String couponRefundId$n$m) {
        this.couponRefundId$n$m = couponRefundId$n$m;
    }

    public Integer getCouponRefundFee$n$m() {
        return couponRefundFee$n$m;
    }

    public void setCouponRefundFee$n$m(Integer couponRefundFee$n$m) {
        this.couponRefundFee$n$m = couponRefundFee$n$m;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }
}
