package com.smallchill.web.model;

import org.beetl.sql.core.annotatoin.Table;
import com.smallchill.core.annotation.BindID;
import com.smallchill.core.base.model.BaseModel;

import javax.persistence.Column;

/**
 * 组织会员
 * Generated by yesong.
 * 2016-10-28 11:08:59
 */
@Table(name = "tb_user_group")
@BindID(name = "id")
@SuppressWarnings("serial")
public class UserGroup extends BaseModel {

    @Column(name = "id")
    private Integer id;

    @Column(name = "user_id")
    private Integer userId;

    @Column(name = "group_id")
    private Integer groupId;

    @Column(name = "vip_end_time")
    private Long vipEndTime = -1L;

    @Column(name = "vip_type")
    private Integer type = 1;

    @Column(name = "join_type")
    private Integer JoinType = 1;

    @Column(name = "create_time")
    private Long createTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getGroupId() {
        return groupId;
    }

    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getVipEndTime() {
        return vipEndTime;
    }

    public void setVipEndTime(Long vipEndTime) {
        this.vipEndTime = vipEndTime;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getJoinType() {
        return JoinType;
    }

    public void setJoinType(Integer joinType) {
        JoinType = joinType;
    }
}
