package com.smallchill.web.model;

import org.beetl.sql.core.annotatoin.Table;
import com.smallchill.core.annotation.BindID;
import com.smallchill.core.base.model.BaseModel;

import javax.persistence.Column;

/**
 * 用户拓展信息
 * Generated by yesong.
 * 2016-12-04 12:08:17
 */
@Table(name = "tb_user_info_extend")
@BindID(name = "id")
@SuppressWarnings("serial")
public class UserInfoExtend extends BaseModel {

    @Column(name = "id")
    private Integer id;
    @Column(name = "user_id")
    private Integer userId;
    @Column(name = "interest_count")
    private Integer interestCount;
    @Column(name = "acquaintance_count")
    private Integer acquaintanceCount;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getInterestCount() {
        return interestCount;
    }

    public void setInterestCount(Integer interestCount) {
        this.interestCount = interestCount;
    }

    public Integer getAcquaintanceCount() {
        return acquaintanceCount;
    }

    public void setAcquaintanceCount(Integer acquaintanceCount) {
        this.acquaintanceCount = acquaintanceCount;
    }
}
