package com.smallchill.platform.service.impl;

import com.smallchill.core.base.service.BaseService;
import com.smallchill.platform.model.UserLogin;
import com.smallchill.platform.service.UserLoginService;
import org.springframework.stereotype.Service;


/**
 * Generated by Blade.
 * 2016-10-18 09:41:36
 */
@Service
public class UserLoginServiceImpl extends BaseService<UserLogin> implements UserLoginService {

}
