package com.smallchill.api.function.service;

import com.smallchill.api.function.modal.ActivityApply;
import com.smallchill.core.base.service.IService;

/**
 * Generated by Blade.
 * 2017-02-13 14:25:58
 */
public interface ActivityApplyService extends IService<ActivityApply>{

}
