package com.smallchill.api.function.service;

import com.smallchill.api.function.modal.GroupInterest;
import com.smallchill.core.base.service.IService;

/**
 * Generated by Blade.
 * 2016-11-11 12:00:57
 */
public interface GroupInterestService extends IService<GroupInterest>{

}
