package com.smallchill.api.function.service;

import com.smallchill.api.function.modal.GroupUserRecord;
import com.smallchill.core.base.service.IService;

/**
 * Generated by Blade.
 * 2016-11-18 18:37:00
 */
public interface GroupUserRecordService extends IService<GroupUserRecord>{

}
