package com.smallchill.api.function.service;

import com.smallchill.api.function.modal.Message;
import com.smallchill.core.base.service.IService;

import java.util.List;

/**
 * Generated by Blade.
 * 2016-10-27 17:24:13
 */
public interface MessageService extends IService<Message>{

    void sendMsgList(Message message, List<Integer> list);

    void sendMsgOne(Message message, Integer userId);

    void sendMsgListByMobile(Message message, List<Integer> list);

    void sendMsgOneByMobile(Message message, List<Integer> list);
}
