package com.smallchill.api.function.service;

import com.smallchill.api.function.modal.vo.Groupvo;
import com.smallchill.api.function.modal.vo.UserVo;

/**
 * Generated by Blade.
 * 2016-11-26 19:17:36
 */
public interface ScanService {

    UserVo scanUser(Integer userId, Integer toUserId);

    Groupvo scanGroup(Integer userId, Integer groupId);

    UserVo identifyMember(Integer userId, Integer toUserId);
}
