package com.smallchill.api.function.service;

import com.smallchill.api.function.modal.Shielding;
import com.smallchill.core.base.service.IService;
import com.smallchill.core.toolbox.Record;

import java.util.List;

/**
 * Generated by Blade.
 * 2017-02-06 11:21:13
 */
public interface ShieldingService extends IService<Shielding>{

    void shieldingByArticleShowId(Integer articleShowId, Integer userId);
    List<Record> listByUserId(Integer userId);
}
