package com.smallchill.api.function.service;

import com.smallchill.api.function.modal.Ufgm;
import com.smallchill.core.base.service.IService;

/**
 * 好友分组成员
 * Generated by yesong.
 * 2016-11-22 18:01:39
 */
public interface UfgmService extends IService<Ufgm>{

}
