package com.smallchill.api.function.service;

import com.smallchill.api.function.modal.UserDomain;
import com.smallchill.core.base.service.IService;


/**
 * Generated by Blade.
 * 2016-10-24 17:47:08
 */
public interface UserDomainService extends IService<UserDomain>{

}
