package com.smallchill.api.function.service;

import com.smallchill.api.function.modal.UserProfessional;
import com.smallchill.core.base.service.IService;


/**
 * Generated by Blade.
 * 2016-10-24 18:05:06
 */
public interface UserprofessionalService extends IService<UserProfessional>{

}
