package com.smallchill.api.function.service;

import com.smallchill.api.function.modal.UserInterest;
import com.smallchill.core.base.service.IService;

/**
 * Generated by Blade.
 * 2016-11-11 11:56:50
 */
public interface UserInterestService extends IService<UserInterest>{

}
