package com.smallchill.api.function.service;

import com.smallchill.api.function.modal.UserLastReadTime;
import com.smallchill.core.base.service.IService;

/**
 * Generated by Blade.
 * 2016-11-04 17:35:21
 */
public interface UserLastReadTimeService extends IService<UserLastReadTime>{

}
