package com.smallchill.api.function.service;

import com.smallchill.api.function.modal.UserFriendGrouping;
import com.smallchill.core.base.service.IService;

/**
 * Generated by Blade.
 * 2016-11-22 17:59:15
 */
public interface UserFriendGroupingService extends IService<UserFriendGrouping>{

    void deleteMemberForDelFriend(Integer userId, Integer friendId);
}
